name: CI
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install
        run: npm install
        
      - name: unit-test
        run: npm run unit-tests
        
      - name: integration-test
        run: npm run integration-tests
        
      - name: Test Report unit
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: mocha Test unit
          path: ./test-results.json
          reporter: mocha-json
      
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'ms-starwars'
          path: '.'
          format: 'HTML'
          others: ''
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.STARWARS2 }}
          SONAR_TOKEN: ${{ secrets.STARWARS }}
        with:
          args: >
            -Dsonar.organization=realflatearth
            -Dsonar.projectKey=realflatearth_ms-starwars
          projectBaseDir: ./
